# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bSu80QoBG2lEDtva9v3uS3KWVqH3LFS0
"""

import pandas as pd
import re

data = pd.read_csv('intelligentGuessingDataSet', encoding = "ISO-8859-1", index_col = 'rownum')

data = data.drop(axis = 1, columns = 'Comments')

data['Email Pattern'] = data['email']
for index, row in data.iterrows():
  row['Email Pattern'] = row['email'].split('@')[0]
  #if row['firstname'][0] in row['email']
  row['Email Pattern'] = re.sub(str(row['firstname']).lower(),'<11>', row['Email Pattern'])
  row['Email Pattern'] = re.sub(str(row['lastname']).lower(), '<22>', row['Email Pattern'])
  
  last =  re.split(' \'\s |\s|-', str(row['lastname']))
  if len(last)>1:
    row['Email Pattern'] = re.sub(last[1].lower(), '<21>', row['Email Pattern'])
    row['Email Pattern'] = re.sub(last[0].lower(), '<20>', row['Email Pattern'])                              

   
  row['Email Pattern'] = re.sub(str(row['firstname'])[:3].lower(), '<11-f31>', row['Email Pattern'], count = 1)  
  row['Email Pattern'] = re.sub(str(row['firstname'])[:2].lower(), '<11-f21>', row['Email Pattern'], count =1)
  row['Email Pattern'] = re.sub(str(row['firstname'])[0].lower(), '<1>', row['Email Pattern'], count = 1)

print(data['Email Pattern'])

data.to_csv("intelligentGuessing")